mod align;
mod anchor;
mod api;
mod db;
mod diff;
mod doc;
mod domain;
mod error;
mod mcp;
mod packet_md;
mod share;
mod store;

#[cfg(test)]
mod http_tests;
#[cfg(test)]
mod pipeline_tests;

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use axum::Router;
use axum::extract::{DefaultBodyLimit, Path, State};
use axum::http::{HeaderValue, StatusCode, header};
use axum::response::{IntoResponse, Redirect, Response};
use axum::routing::get;
use rust_embed::RustEmbed;

use api::{AppState, Auth, Config, Shared};
use store::Store;

#[derive(RustEmbed)]
#[folder = "../web/dist"]
struct WebDist;

const REPORT_CSS: &str = include_str!("../../web/src/styles/report.css");
const SHARE_CSS: &str = include_str!("../static/share.css");

pub fn app(state: Shared) -> Router {
    Router::new()
        .merge(api::router())
        .route("/mcp", get(mcp::get).post(mcp::post))
        .route("/s/{token}", get(share::page))
        .route("/s/{token}/a/{*rest}", get(share::asset))
        .route("/a/{report}/{*rest}", get(asset))
        .route("/static/report.css", get(|| async { css(REPORT_CSS) }))
        .route("/static/share.css", get(|| async { css(SHARE_CSS) }))
        .route("/", get(|| async { Redirect::temporary("/app") }))
        .route("/app", get(spa_index))
        .route("/app/", get(spa_index))
        .route("/app/{*path}", get(spa))
        .layer(DefaultBodyLimit::max(32 * 1024 * 1024))
        .with_state(state)
}

fn css(body: &'static str) -> Response {
    ([(header::CONTENT_TYPE, "text/css; charset=utf-8"), (header::CACHE_CONTROL, "public, max-age=300")], body)
        .into_response()
}

/// Report assets for the workbench and agents. Share pages use `/s/<token>/a/...` instead.
async fn asset(State(s): State<Shared>, _: Auth, Path((report, rest)): Path<(String, String)>) -> Response {
    match s.store().asset(&report, &rest) {
        // Content-addressed URLs never change meaning; bare names follow the latest upload.
        Ok((mime, bytes, immutable)) => {
            asset_response(&mime, bytes, if immutable { "private, max-age=31536000, immutable" } else { "private, no-cache" })
        }
        Err(_) => StatusCode::NOT_FOUND.into_response(),
    }
}

pub fn asset_response(mime: &str, bytes: Vec<u8>, cache: &'static str) -> Response {
    let mut resp = bytes.into_response();
    let h = resp.headers_mut();
    h.insert(header::CONTENT_TYPE, HeaderValue::from_str(mime).unwrap_or(HeaderValue::from_static("application/octet-stream")));
    h.insert(header::CACHE_CONTROL, HeaderValue::from_static(cache));
    h.insert("x-content-type-options", HeaderValue::from_static("nosniff"));
    h.insert(header::CONTENT_SECURITY_POLICY, HeaderValue::from_static("default-src 'none'; sandbox"));
    resp
}

fn embedded(path: &str) -> Option<Response> {
    let file = WebDist::get(path)?;
    let mime = mime_guess::from_path(path).first_or_octet_stream();
    let cache = if path.starts_with("assets/") { "public, max-age=31536000, immutable" } else { "no-cache" };
    Some(
        (
            [
                (header::CONTENT_TYPE, HeaderValue::from_str(mime.as_ref()).unwrap()),
                (header::CACHE_CONTROL, HeaderValue::from_static(cache)),
            ],
            file.data.into_owned(),
        )
            .into_response(),
    )
}

async fn spa_index() -> Response {
    embedded("index.html").unwrap_or_else(|| {
        (StatusCode::SERVICE_UNAVAILABLE, "workbench not built: run `npm run build` in web/").into_response()
    })
}

async fn spa(Path(path): Path<String>) -> Response {
    match embedded(&path) {
        Some(r) => r,
        None if path.starts_with("assets/") => StatusCode::NOT_FOUND.into_response(),
        None => spa_index().await,
    }
}

fn env_or(key: &str, default: &str) -> String {
    std::env::var(key).ok().filter(|v| !v.is_empty()).unwrap_or_else(|| default.to_string())
}

/// Missing secrets are generated once and kept in `<data>/secrets.json` so first runs need no setup.
/// The flag is true only when the value was generated by this call.
fn load_secret(data_dir: &std::path::Path, key: &str, env: &str) -> (String, bool) {
    if let Ok(v) = std::env::var(env) {
        if !v.is_empty() {
            return (v, false);
        }
    }
    let path = data_dir.join("secrets.json");
    let mut secrets: serde_json::Map<String, serde_json::Value> = std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    if let Some(v) = secrets.get(key).and_then(|v| v.as_str()) {
        return (v.to_string(), false);
    }
    let value = db::random_token();
    secrets.insert(key.to_string(), value.clone().into());
    let _ = write_private(&path, serde_json::to_string_pretty(&secrets).unwrap_or_default().as_bytes());
    (value, true)
}

/// Restricts permissions before any bytes are written so the secrets are never readable by others.
fn write_private(path: &std::path::Path, contents: &[u8]) -> std::io::Result<()> {
    use std::io::Write;
    let mut opts = std::fs::OpenOptions::new();
    opts.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
        opts.mode(0o600);
        let file = opts.open(path)?;
        // `mode` only applies on creation; an existing file keeps its old permissions otherwise.
        file.set_permissions(std::fs::Permissions::from_mode(0o600))?;
        return (&file).write_all(contents);
    }
    #[cfg(not(unix))]
    opts.open(path)?.write_all(contents)
}

#[tokio::main]
async fn main() {
    let addr: SocketAddr = env_or("GALLEY_ADDR", "127.0.0.1:7860").parse().expect("GALLEY_ADDR must be host:port");
    let data_dir = PathBuf::from(env_or("GALLEY_DATA", "./data"));
    std::fs::create_dir_all(data_dir.join("assets")).expect("cannot create data directory");

    let (owner_password, new_password) = load_secret(&data_dir, "owner_password", "GALLEY_PASSWORD");
    let config = Config {
        owner_password,
        agent_token: load_secret(&data_dir, "agent_token", "GALLEY_AGENT_TOKEN").0,
        public_url: env_or("GALLEY_PUBLIC_URL", &format!("http://{addr}")),
        secure_cookies: env_or("GALLEY_PUBLIC_URL", "").starts_with("https://"),
    };
    let conn = db::open(&data_dir.join("galley.db")).expect("cannot open database");
    let mut store = Store::new(conn, data_dir.join("assets"));
    match store.migrate_legacy_assets() {
        Ok(0) => {}
        Ok(n) => println!("moved {n} assets to content-addressed storage"),
        Err(e) => eprintln!("asset migration failed: {e}"),
    }
    let state = Arc::new(AppState { store: Mutex::new(store), config: config.clone() });

    let listener = tokio::net::TcpListener::bind(addr).await.expect("cannot bind");
    println!("galley listening on {}", config.public_url);
    println!("  workbench: {}/app", config.public_url);
    println!("  MCP:       {}/mcp", config.public_url);
    if std::env::var("GALLEY_PASSWORD").is_err() || std::env::var("GALLEY_AGENT_TOKEN").is_err() {
        println!("  secrets:   {} (owner_password, agent_token)", data_dir.join("secrets.json").display());
    }
    // Shown once, on the run that generated it, so a first-time user can log in without opening the file.
    if new_password {
        println!("  password:  {} (first run only; also saved in secrets.json)", config.owner_password);
    }
    axum::serve(listener, app(state))
        .with_graceful_shutdown(async {
            let _ = tokio::signal::ctrl_c().await;
        })
        .await
        .expect("server error");
}
